version: '3.9'

services:
  postgres:
    image: postgres
    volumes:
      - ./initial_db.sql:/docker-entrypoint-initdb.d/initial_db.sql
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"